---
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
matrix:
  include:
  - language: ruby
    rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes
    script: "bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
  - language: ruby
    rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES=yes
    script: "bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
  - language: ruby
    rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 6.0" STRICT_VARIABLES=yes
    script: "bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
notifications:
  email:
    recipients:
      - 'alexharv074@gmail.com'
    on_success: never
    on_failure: always
