---
language: ruby
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
matrix:
  include:
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5.0"
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
notifications:
  email: false
